### PR TITLE
Add Cairo LoC

### PR DESCRIPTION
**Pull request by misicnenad**

### CODE REVIEW

**Comment by misicnenad** [comment]
@ErikSchierboom THANK YOU *sigh of relief*

I've been trying to figure out what I am doing wrong haha

**Comment by ErikSchierboom** [comment]
@misicnenad Seems like the test is failing

**Comment by misicnenad** [comment]
@ErikSchierboom fixed the code, tests are passing

**Comment by ErikSchierboom** [comment]
Thanks

**Pull request merged**
